version: "3.5"

services:
  validate:
    image: renovate/renovate:19.38.4-slim@sha256:2199731a311342c37fc14dd204e8bfddbb72dfe479f2f06c60db476836449e9a
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
