version: "3.5"

services:
  validate:
    image: renovate/renovate:19.37.0-slim@sha256:4ac7ef2fa345cd4a784cc81656abad334dcbc3b4491cc520aa97b75590803a11
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
