version: "3.5"

services:
  validate:
    image: renovate/renovate:19.34.2-slim@sha256:debeb37d7c24827aa5cbb08fcdb45a8b0a006a8343677a8aeb490052a429a3d0
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
