version: "3.5"

services:
  validate:
    image: renovate/renovate:19.65.2-slim@sha256:afb669d2e0f74bd7964af05cb7aa3a1571988193de6cb09d839a8ea5175ba217
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
