version: "3.5"

services:
  validate:
    image: renovate/renovate:19.30.10-slim@sha256:f4f6b2260e9522ca3d14a39b7c742e372545967eafab3a5e2274085c65ba5967
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
