version: "3.5"

services:
  validate:
    image: renovate/renovate:19.66.12-slim@sha256:1b9a672ac5d272e9fe8e3bf415855510ae9020070e42d506a97d21755edc5d8a
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
