version: "3.5"

services:
  validate:
    image: renovate/renovate:19.50.0-slim@sha256:abbeedee227298fb29ddb855196ae831271e10f3ca059ce3fab7e481311ae00b
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
