version: "3.5"

services:
  validate:
    image: renovate/renovate:21.3.0-slim@sha256:d994f59f4f5227374d6b60b6faca7d9de33b82649017be282ff76be6e59ead04
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/default.json
    entrypoint: node_modules/renovate/dist/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
