version: "3.5"

services:
  validate:
    image: renovate/renovate:19.59.2-slim@sha256:a0c02171008d45dbda5cc38673084dcd8a772e37717b800acc24da020b1bdc12
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
