version: "3.5"

services:
  validate:
    image: renovate/renovate:19.54.1-slim@sha256:ca75d2d3fb11c916502208a498926db740cab96e4cd7611abf68df396437a007
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
