version: "3.5"

services:
  validate:
    image: renovate/renovate:19.107.3-slim@sha256:46096edf6a56d31d91f03c757b6f3fd0a898aded9331c68909cdf62ae2492b5b
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/default.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
