version: "3.5"

services:
  validate:
    image: renovate/renovate:19.65.1-slim@sha256:879a730ebe15ba4957d397c5df4a7464414bd3c87cb9ee6cb2d9b1d4ca4c1ac1
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
