version: "3.5"

services:
  validate:
    image: renovate/renovate:19.61.7-slim@sha256:8e37a38c1a1fe932c036f0a98011fac6c642f20fd567f69bd47678317536256e
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
