version: "3.5"

services:
  validate:
    image: renovate/renovate:19.65.9-slim@sha256:a25475a7ee8ec713c3ebd063bf5a751373add1682fb494df130875815ffa3067
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
