version: "3.5"

services:
  validate:
    image: renovate/renovate:19.228.2-slim@sha256:27f161f2ef5d045b4dcb4822affd6215965e008b2ba2dd5f52bd0c8c1bbcbb51
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/default.json
    entrypoint: node_modules/renovate/bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
