version: "3.5"

services:
  validate:
    image: renovate/renovate:19.225.3-slim@sha256:f10516c249cff79299096cd934015a11689dce4f83f6430029b5676b13a6cfe1
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/default.json
    entrypoint: node_modules/renovate/bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
