version: "3.5"

services:
  validate:
    image: renovate/renovate:19.20.3-slim@sha256:6e1cb3ceb5e0c72663238f776633fec744f3afbe560646966920c1aa7a131cc7
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
