version: "3.5"

services:
  validate:
    image: renovate/renovate:21.4.0-slim@sha256:07aff2bbab0966fe9fdb2e062f326be397c2b4bd022a50f67b36f770b76513da
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/default.json
    entrypoint: node_modules/renovate/dist/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
