version: "3.5"

services:
  validate:
    image: renovate/renovate:19.33.3-slim@sha256:a0c342511d72baf39000a72da0290f490509cd4fbd0bc5ec0c9e4aeb86cb57df
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
