version: "3.5"

services:
  validate:
    image: renovate/renovate:20.25.8-slim@sha256:8e18647e5fcdf7ec6307246b55e7d698f41c4cce16b6adc4b7dfb900816e8b55
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/default.json
    entrypoint: node_modules/renovate/dist/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
