version: "3.5"

services:
  validate:
    image: renovate/renovate:19.34.4-slim@sha256:ac6e6227151fbccf5aeded5bef36e8f24ca180a06874a7d562b9750a00256137
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
