version: "3.5"

services:
  validate:
    image: renovate/renovate:19.59.5-slim@sha256:ff8f60a22e3182c85a5d37968f78e996bf8795ac98dd8b843f8d129994d2c6e1
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
