version: "3.5"

services:
  validate:
    image: renovate/renovate:19.176.1-slim@sha256:9bc8ca870a67b3d589fe4f8281d01235fd14ce2c57d5c570e273cb947c681775
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/default.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
