version: "3.5"

services:
  validate:
    image: renovate/renovate:19.64.4-slim@sha256:09a0a7fdd9cf714518334ebc2c63cb666625f015013f095adec0de834f052dd1
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
