version: "3.5"

services:
  validate:
    image: renovate/renovate:19.58.5-slim@sha256:563fadfbfae6695f7fcaf65e3026a19dcf391b2fdb74966da0f3816cc1ebf5cd
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
