version: "3.5"

services:
  validate:
    image: renovate/renovate:19.59.1-slim@sha256:c82fc8cadc1de913b7519e32b61969fe1c568018ddfb7957238464a831656f08
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
