version: "3.5"

services:
  validate:
    image: renovate/renovate:19.40.2-slim@sha256:1bfbd2488ccdc78fbe8519af8d5817bcc36d33ec2301f7943902c73b2b45a86b
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
