version: "3.5"

services:
  validate:
    image: renovate/renovate:19.30.4-slim@sha256:75e0ff8d1186602a22c1097daaeab68a9c82bfee5cd471338336195dda29479c
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
