version: "3.5"

services:
  validate:
    image: renovate/renovate:19.60.1-slim@sha256:3611777633aeeb2f5de7eabebffd6005edec8af7457312936f2597dc1d36aa96
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
