version: "3.5"

services:
  validate:
    image: renovate/renovate:19.149.0-slim@sha256:d8df7b5096b77d6a32a3b57aaa8295a2926ff87d1bbb76a4c47efee0600afb41
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/default.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
