version: "3.5"

services:
  validate:
    image: renovate/renovate:19.44.2-slim@sha256:a456de0f4b3f5f27bbd8d8b21c28e2bbaa9cd9a4591b1eac334d77eacc193251
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
