version: "3.5"

services:
  validate:
    image: renovate/renovate:19.64.0-slim@sha256:6ae7ee8051ce2d109534cd002372e6dec5ff4de07413fcefc89e44fa010882b9
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
