version: "3.5"

services:
  validate:
    image: renovate/renovate:19.49.0-slim@sha256:abc07fe171e28b91aceea710c2e4db65ec4d4bce759de1d113482420f41a0155
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
