version: "3.5"

services:
  validate:
    image: renovate/renovate:19.221.0-slim@sha256:f6ac338f673bfa9ef7b30b9774518d7cd607fbb0a28bd1046019a0dfe1cffc9e
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/default.json
    entrypoint: node_modules/renovate/bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
