version: "3.5"

services:
  validate:
    image: renovate/renovate:19.89.3-slim@sha256:0ff11ff4f8cda09297c4df91ae3b4ed6f76efef2f284230df1bf5210e5adb269
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/default.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
