version: "3.5"

services:
  validate:
    image: renovate/renovate:19.188.0-slim@sha256:936ef8c027f9fe66a83ce3496ba2e5ce5f1d517e3d5984e94fe669fa8921fdad
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/default.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
