version: "3.5"

services:
  validate:
    image: renovate/renovate:19.52.2-slim@sha256:87e97827dc10e2534507af7e21d6d6660fcc199aba209462413330c7609f9dcd
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
