version: "3.5"

services:
  validate:
    image: renovate/renovate:19.107.1-slim@sha256:d0e24dff916943647f93afa27df6e848b2b414ad8071e67e3bee29a773cd09c4
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/default.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
