version: "3.5"

services:
  validate:
    image: renovate/renovate:19.33.2-slim@sha256:c5cc3540186b9cbc4d4e00f8bcd4144468c35def5ee0aa9b989044c2ea58c618
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
