version: "3.5"

services:
  validate:
    image: renovate/renovate:19.66.2-slim@sha256:7eaa1eee526a820d77fa338d2161bb651328e7a0390295e54af12b3bac3e8c32
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
