version: "3.5"

services:
  validate:
    image: renovate/renovate:19.114.1-slim@sha256:3f5cf7dffde4f7295e136e54ac68206f94947bd97dbc865068bb2ac2354475fc
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/default.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
