version: "3.5"

services:
  validate:
    image: renovate/renovate:19.219.6-slim@sha256:6ede187cfb5eb4c574ee124d7c42558c5934022cf8bd0ea666f9c50477fe0e4e
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/default.json
    entrypoint: node_modules/renovate/bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
