version: "3.5"

services:
  validate:
    image: renovate/renovate:19.64.2-slim@sha256:52d3892d5c6ae53d8993edd28fcbb565c172535600b1049b05cd8cd0a76c2a5e
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/renovate.json
    entrypoint: bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
