version: "3.5"

services:
  validate:
    image: renovate/renovate:19.239.11-slim@sha256:1985234a80b09ce8526803d4834df75dc4de3db2ad69685a6bc0a240501f682a
    environment:
      RENOVATE_CONFIG_FILE: /var/src/renovate-config/default.json
    entrypoint: node_modules/renovate/bin/config-validator.js
    volumes:
      - type: bind
        source: .
        target: /var/src/renovate-config
